-- total customers by countries

select 
	country,
	count(customer_key) as total_customers	
from 
	gold.dim_customers
group by country
order by total_customers desc
	

-- total customers by gender
select 
	gender,
	count(customer_id) as total_customers
from 
	gold.dim_customers
group by gender
order by total_customers desc

-- total products by category
select 
	category,
	count(product_name) as total_products
from 
	gold.dim_products
group by category 
order by total_products desc
	

-- average costs in each category?
select  
	category,
	avg(cost) as average_cost 
from 
	gold.dim_products
group by 
	category
order by 
	average_cost desc	


-- total revenue generated for each category?
select
	prod.category,
	coalesce(sum(sales.sales_amount),0) as total_revenue

from 
	gold.dim_products prod
left join 
	gold.fact_sales sales
on 
	prod.product_id = sales.product_key
group by 
	prod.category
order by 
	total_revenue desc

-- total revenue generated by each customer?
select * from gold.fact_sales

select 
	cust.customer_key,
	cust.first_name,
	cust.last_name,
	sum(sales.sales_amount)as total_revenue

from 
	gold.fact_sales sales 
left join 
	gold.dim_customers cust
on 
	cust.customer_key = sales.customer_key
group by 
	cust.customer_key,
	cust.first_name,
	cust.last_name
order by 
	total_revenue desc

-- distribution of sold items across countries?
select 
	cust.country,
	sum(sales.sales_amount)as total_revenue

from 
	gold.fact_sales sales 
left join 
	gold.dim_customers cust
on 
	cust.customer_key = sales.customer_key
group by 
	cust.country
order by 
	total_revenue desc